version: '3.7'

services:

 consul:
  image: consul:latest
  volumes:
  - ./consul.json:/etc/consul/consul.json
  command: consul agent -config-file=/etc/consul/consul.json -server -client 0.0.0.0 -ui -bootstrap-expect=1 -data-dir=/consul/data -datacenter=blr
  ports:
    - "8500:8500"
    - "8600:8600/udp"
  networks:
    - back

 matching-engine:
  build: matching-engine
  depends_on:
  - consul
  ports:
  - "8980"
  - "8981"
  - "8982"
  - "8983"
  - "8984"
  - "8082:80"
  - "9997:9997"
  networks:
  - back

 trade-execution:
   build: trade-execution
   depends_on:
   - consul
   ports:
   - "8980"
   - "8982"
   - "8983"
   - "8984"
   - "8081:80"
   - "8080:8080"
   - "9998:9998"
   networks:
   - back

 pricing:
   build: pricing
   depends_on:
   - consul
   ports:
   - "8981"
   - "8084:80"
   - "8085:8085"
   - "9999:9999"
   networks:
   - back

 market:
   build: market
   depends_on:
    - consul
   ports:
   - "9996:9996"
   networks:
   - back

 docs:
     build: docs
     ports:
     - "8090:80"
     networks:
     - back

 scope:
     image: weaveworks/scope:latest
     hostname: weave-scope
     pid: "host"
     privileged: true
     ports:
       - "4040:4040"
     expose:
       - "4040"
     labels:
       - "works.weave.role=system"
     volumes:
       - "/var/run/docker.sock:/var/run/docker.sock:rw"
     command:
       - "--probe.docker"
       - "true"
     networks:
       - back

 prom:
  image: prom/prometheus:latest
  volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  command: '--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus'
  ports:
  - 9090:9090
  depends_on:
  - matching-engine
  networks:
   - back

 grafana:
   image: grafana/grafana
   ports:
    - 3000:3000
   depends_on:
    - prom
   networks:
    - back

networks:
 back:
  driver: bridge



