version: '3.7'

services:

 matching-engine:
  build: matching-engine
  external_links:
  - consul
  environment:
  - TCP_PORT
  - HTTP_MONITORING_PORT
  - DB_PATH
  - CONSUL_URL
  ports:
  - ${TCP_PORT}
  - "8981"
  - "8982"
  - "8983"
  - "8984"
  - "8082:80"
  - "9997:9997"
  volumes:
  - ./target/var/lib/ldb/data:/var/lib/ldb/data
  networks:
  - back
  - mutualized

 trade-execution:
   build: trade-execution
   external_links:
   - consul
   env_file:
   - trade-execution.env
   ports:
   - ${TCP_PORT}
   - "8982"
   - "8983"
   - "8984"
   - "8081:80"
   - "8080:8080"
   - "9998:9998"
   networks:
   - back
   - mutualized

 pricing:
   build: pricing
   external_links:
   - consul
   env_file:
   - pricing.env
   ports:
   - "8981"
   - "8084:80"
   - "8085:8085"
   - "9999:9999"
   networks:
   - back
   - mutualized

 market:
   build: market
   external_links:
    - consul
   env_file:
    - market.env
   ports:
   - "9996:9996"
   networks:
   - back
   - mutualized

 docs:
     build: docs
     ports:
     - "8090:80"
     networks:
     - back
     - mutualized

networks:
 back:
  driver: bridge
  external: true
 mutualized:
  external: true



